#!/usr/bin/env python3
"""
build_docs.py — emit human-readable docs from data/indicators.yaml.

Outputs:
  - docs/roots.md              master root catalog by family
  - docs/composites.md         master composite catalog by indicator + tier
  - docs/redundancy.md         drift table (composition collisions + internal-impl)
  - docs/visual-trees/<id>.txt per-indicator ASCII dependency trees
  - INDICATORS_INDEX.md        entry point at repo root

All files are regenerated on each run. Source of truth: data/indicators.yaml.

Usage:  python3 tools/build_docs.py
"""

from __future__ import annotations

import datetime as _dt
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml

REPO = Path(__file__).resolve().parent.parent
YAML_PATH = REPO / "data" / "indicators.yaml"
DOCS = REPO / "docs"
TREES_DIR = DOCS / "visual-trees"
INDEX_PATH = REPO / "INDICATORS_INDEX.md"

HEADER = "_Auto-generated by `tools/build_docs.py` from `data/indicators.yaml`. Edit the YAML; re-run the script._"


def short(text: Any, n: int = 100) -> str:
    s = str(text or "").replace("\n", " ").replace("|", "/")
    return s if len(s) <= n else s[: n - 1] + "…"


def operands_of(c: dict) -> list[str]:
    out: list[str] = []
    comp = c.get("composition") or {}
    if isinstance(comp, dict):
        for op in comp.get("operands") or []:
            if isinstance(op, str):
                out.append(op)
            elif isinstance(op, dict):
                if "of" in op and isinstance(op["of"], str):
                    out.append(op["of"])
                for sub in op.get("operands") or []:
                    if isinstance(sub, str):
                        out.append(sub)
    return out


def build_roots_md(data: dict) -> str:
    roots = data.get("roots") or []
    by_family: dict[str, list[dict]] = defaultdict(list)
    for r in roots:
        fam = r.get("family") or "other"
        by_family[fam].append(r)

    lines = ["# Roots — master catalog", "", HEADER, "",
             f"**Total roots: {len(roots)}** across {len(by_family)} families.", ""]

    family_order = ["push", "candle", "rvol", "fvg", "hv", "gzi",
                    "displacement", "structural", "oscillator", "other"]
    seen_families = set()

    def render_family(fam: str, recs: list[dict]) -> list[str]:
        out = [f"## Family: `{fam}` ({len(recs)} roots)", "",
               "| Canonical | Indicator | Plain English | Offset | Stage | Source |",
               "|---|---|---|---|---|---|"]
        for r in sorted(recs, key=lambda x: x.get("id", "")):
            cid = r.get("id", "?")
            ind = r.get("in_indicator", "?")
            pe = short(r.get("plain_english") or r.get("boolean_summary") or "", 80)
            off = r.get("plot_offset", r.get("offset", "?"))
            stage = r.get("lifecycle_stage", 2)
            src = r.get("pine_source_line_range", "?")
            out.append(f"| `{cid}` | `{ind}` | {pe} | {off} | {stage} | {src} |")
        out.append("")
        return out

    for fam in family_order:
        if fam in by_family:
            seen_families.add(fam)
            lines.extend(render_family(fam, by_family[fam]))
    for fam in sorted(by_family):
        if fam not in seen_families:
            lines.extend(render_family(fam, by_family[fam]))

    return "\n".join(lines) + "\n"


def build_composites_md(data: dict) -> str:
    composites = data.get("composites") or []
    by_indicator: dict[str, list[dict]] = defaultdict(list)
    for c in composites:
        by_indicator[c.get("in_indicator", "?")].append(c)

    lines = ["# Composites — master catalog", "", HEADER, "",
             f"**Total composites: {len(composites)}** across {len(by_indicator)} indicators.", ""]

    for ind in sorted(by_indicator):
        recs = by_indicator[ind]
        by_tier: dict[Any, list[dict]] = defaultdict(list)
        for c in recs:
            by_tier[c.get("tier", "?")].append(c)
        lines.append(f"## `{ind}` ({len(recs)} composites)")
        lines.append("")
        for tier in sorted(by_tier, key=lambda t: (str(t),)):
            lines.append(f"### Tier {tier} ({len(by_tier[tier])})")
            lines.append("")
            lines.append("| Canonical | Composition | Operands | Offset |")
            lines.append("|---|---|---|---|")
            for c in sorted(by_tier[tier], key=lambda x: x.get("id", "")):
                cid = c.get("id", "?")
                comp = c.get("composition") or {}
                ctype = comp.get("type", "?") if isinstance(comp, dict) else "?"
                ops = operands_of(c)
                ops_short = short(", ".join(f"`{o}`" for o in ops[:6]) + (" …" if len(ops) > 6 else ""), 120)
                off = c.get("plot_offset", c.get("offset", "?"))
                lines.append(f"| `{cid}` | {ctype} | {ops_short} | {off} |")
            lines.append("")
        lines.append("")

    return "\n".join(lines) + "\n"


def build_redundancy_md(data: dict) -> str:
    roots = data.get("roots") or []
    composites = data.get("composites") or []

    # (a) Composition / namespace collisions: same un-prefixed name, different provenance
    by_short_name: dict[str, list[dict]] = defaultdict(list)
    for r in roots:
        cid = r.get("id", "")
        if "::" in cid:
            short_name = cid.split("::", 1)[1]
            by_short_name[short_name].append(r)
    for c in composites:
        cid = c.get("id", "")
        if "::" in cid:
            short_name = cid.split("::", 1)[1]
            by_short_name[short_name].append(c)

    collisions = {n: recs for n, recs in by_short_name.items() if len(recs) > 1}

    lines = ["# Redundancy & Drift", "", HEADER, "",
             "Two tables. **(a)** name collisions — same primitive name appearing under two or more provenance namespaces. **(b)** internal-implementation drift — same canonical name with different underlying Pine math across files.", ""]

    lines.append("## (a) Name collisions across indicators")
    lines.append("")
    if not collisions:
        lines.append("_No name collisions detected._")
        lines.append("")
    else:
        lines.append(f"**{len(collisions)} colliding names.** Each row groups all canonical IDs that share an unqualified name.")
        lines.append("")
        lines.append("| Short name | Occurrences | Verdict | Recommendation |")
        lines.append("|---|---|---|---|")
        for short_name in sorted(collisions):
            recs = collisions[short_name]
            occ = "; ".join(f"`{r.get('id','?')}` (in {r.get('in_indicator','?')})" for r in recs)
            verdict = "drifted? — verify per-record"
            rec = "designate one canonical, mark others as variants in YAML"
            lines.append(f"| `{short_name}` | {short(occ, 200)} | {verdict} | {rec} |")
        lines.append("")

    lines.append("## (b) Internal-implementation drift inside roots")
    lines.append("")
    lines.append("Roots whose internal Pine implementation may have diverged across the indicators that NAME them. Detection method: byte-diff each root's source-line range across files.")
    lines.append("")
    lines.append("Most-likely-drift candidates (per Stage-1 agent findings):")
    lines.append("")
    drift_candidates = [
        ("PUP / PPD",
         "Defined in both `b2b-pup` (L73-L79 — locally redefined) and `hvd-pbj-ppd` (Engine 5). The 3%-bar + 10-bar opposite-volume rule is the same conceptually; the bible designates `b2b-pup::PUP` / `b2b-pup::PPD` as canonical pending Stage-1.5 byte-diff.",
         "Stage 6.8 — pick canonical, mark other as alias"),
        ("PBJ / PB",
         "Defined in `hvd-pbj-ppd` (`HVDPBJPPD_2026-05-10_THE_ONLY_ONE.pine` is canonical per filename; predecessor `4.26.1244am` is `drifted-subset`). Also referenced in `b2b-pup` Engine D — verify identical implementation.",
         "Stage 6.8 — confirm parity vs THE_ONLY_ONE"),
        ("RVOL family (SAAB, Kratos, RVOL1x, GS, MOAB, Pentagon, WTC, Hiroshima, Nagasaki)",
         "Canonical: `heavy-pentagon::*`. `heavy-combo-toggles` lifts verbatim (verified by extraction agent). `b2b-pup` Engine E and `hvd-pbj-ppd` USE pipeline have inline copies — verify drift.",
         "Stage 6.8 — confirm parity vs heavy-pentagon"),
        ("GZI / HV / FVG (bull/bear)",
         "Canonical: `hv-fvg-gz1-og::*`. `proximity-gzi-hv` is a stripped variant (parity-checked OK in extraction agent: byte-identical except dashboard removal + title color). Other indicators may have drifted copies.",
         "Stage 6.8 — confirm parity for non-stripped consumers"),
        ("FAUNA decomposition `(MB OR RE OR TA) AND NOT (GG OR TR OR ES OR GDR)`",
         "Locked in `ultra-combo` (L730-L732 bull, L746-L748 bear). Squarify and B2B PUP use FAUNA — verify they reference the same MB/RE/TA/GG/TR/ES/GDR primitives, not drifted variants.",
         "Stage 6.8 — verify FAUNA component parity"),
        ("Pentagon vs anyBearPent",
         "Namespace collision: `Pentagon` is the RVOL Reg@Time tier; `anyBearPent` (in older HVDPBJPPD) is a bear platform mirror of FLOOR. Distinct concepts; same prefix.",
         "Stage 6.1 — rename `anyBearPent` → `anyBear2F`"),
        ("Trinity vs Neo (Matrix family)",
         "Resolved by Squarify extraction (L1215-L1216): Neo = matrix-number AND FAUNA; Trinity = matrix-number AND NOT FAUNA AND directional close. Both feed `matrix_any_bull` → CS3/CS4 → Unified Combo.",
         "No action — definition is now canonical in YAML"),
        ("TNT-OD v2 vs v3",
         "v3 features (Apex, Failed-Apex Flip, T1 Relay/Stack) live in `TNT_OD_v3.pine` (148KB) but the file currently designated as canonical (`TNT_Opening_Drive_OD_v3_2026-05-04.pine`, 122KB) is internally titled v2 and lacks them. Stage 6.4 must reconcile.",
         "Stage 6.4 — pick the right canonical TNT-OD"),
    ]
    lines.append("| Drift candidate | Notes | Stage-6 action |")
    lines.append("|---|---|---|")
    for name, notes, action in drift_candidates:
        lines.append(f"| **{name}** | {notes} | {action} |")
    lines.append("")
    return "\n".join(lines) + "\n"


def build_visual_tree_for(ind_id: str, ind: dict, all_records: dict[str, dict]) -> str:
    lines = [f"VISUAL TREE — {ind_id}",
             "=" * (15 + len(ind_id)),
             f"File: {ind.get('file', '?')}",
             f"Pine v{ind.get('pine_version', '?')}  ·  {ind.get('line_count', '?')} lines  ·  overlay={ind.get('overlay', '?')}",
             f"Purpose: {ind.get('one_line_purpose', '?')}",
             "",
             "ROOTS",
             "-----"]
    for r in ind.get("roots") or []:
        cid = r.get("id", "?")
        fam = r.get("family", "?")
        off = r.get("plot_offset", r.get("offset", "?"))
        pe = short(r.get("plain_english") or "", 70)
        lines.append(f"  ◆ {cid}    [{fam} · offset={off}]")
        lines.append(f"      {pe}")
    lines.append("")
    lines.append("COMPOSITES (by tier)")
    lines.append("-----")
    by_tier: dict[Any, list[dict]] = defaultdict(list)
    for c in ind.get("composites") or []:
        by_tier[c.get("tier", "?")].append(c)
    for tier in sorted(by_tier, key=lambda t: str(t)):
        lines.append(f"  Tier {tier}:")
        for c in by_tier[tier]:
            cid = c.get("id", "?")
            off = c.get("plot_offset", c.get("offset", "?"))
            ops = operands_of(c)
            comp = c.get("composition") or {}
            ctype = comp.get("type", "?") if isinstance(comp, dict) else "?"
            pe = short(c.get("plain_english") or "", 70)
            lines.append(f"    ● {cid}    [offset={off} · {ctype}]")
            if pe:
                lines.append(f"        {pe}")
            for o in ops[:8]:
                marker = "└──" if o == ops[-1] else "├──"
                lines.append(f"        {marker} {o}")
            if len(ops) > 8:
                lines.append(f"        └── … and {len(ops) - 8} more")
        lines.append("")
    lines.append("")

    cross = ind.get("cross_indicator_dependencies") or []
    if cross:
        lines.append("CROSS-INDICATOR DEPENDENCIES")
        lines.append("-----")
        if isinstance(cross, list):
            for x in cross[:30]:
                lines.append(f"  → {x if isinstance(x, str) else x}")
            if len(cross) > 30:
                lines.append(f"  … and {len(cross) - 30} more")
        lines.append("")

    return "\n".join(lines) + "\n"


def build_visual_trees(data: dict) -> dict[str, str]:
    out: dict[str, str] = {}
    all_records: dict[str, dict] = {}
    for r in data.get("roots") or []:
        if isinstance(r, dict) and r.get("id"):
            all_records[r["id"]] = r
    for c in data.get("composites") or []:
        if isinstance(c, dict) and c.get("id"):
            all_records[c["id"]] = c
    for ind in data.get("indicators") or []:
        ind_id = ind.get("id", "?")
        out[ind_id] = build_visual_tree_for(ind_id, ind, all_records)
    return out


def build_index_md(data: dict) -> str:
    indicators = data.get("indicators") or []
    n_roots = sum(len(i.get("roots") or []) for i in indicators)
    n_comps = sum(len(i.get("composites") or []) for i in indicators)
    today = _dt.date.today().isoformat()

    lines = [
        "# Indicators Bible — Index",
        "",
        f"_Generated {today}. Source of truth: [`data/indicators.yaml`](./data/indicators.yaml). " + HEADER + "_",
        "",
        f"- **{len(indicators)} indicator families**",
        f"- **{n_roots} roots** ([catalog](./docs/roots.md))",
        f"- **{n_comps} composites** ([catalog](./docs/composites.md))",
        f"- **76 lineage cards** ([index](./docs/lineage/INDEX.md))",
        "",
        "## Quick links",
        "",
        "- [`docs/glossary.md`](./docs/glossary.md) — cross-cutting concepts; bar lifecycle; non-roots.",
        "- [`docs/roots.md`](./docs/roots.md) — every root, by family.",
        "- [`docs/composites.md`](./docs/composites.md) — every composite, by indicator + tier.",
        "- [`docs/redundancy.md`](./docs/redundancy.md) — drift table.",
        "- [`docs/version-control-diagnosis.md`](./docs/version-control-diagnosis.md) — file-system / branch issues.",
        "- [`docs/lineage/INDEX.md`](./docs/lineage/INDEX.md) — per-top-level-composite lineage cards.",
        "- [`docs/visual-trees/`](./docs/visual-trees/) — per-indicator ASCII dependency trees.",
        "- [`bible-input/MANIFEST.md`](./bible-input/MANIFEST.md) — canonical Pine source per indicator family + branch provenance.",
        "- [`UNLIMITED_APPROVAL.md`](./UNLIMITED_APPROVAL.md) — execution bundle (Stage 0 → Stage 6 plan).",
        "",
        "## Per-indicator summary",
        "",
        "| # | Indicator | File | Pine | Lines | Roots | Composites | One-line |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for i, ind in enumerate(sorted(indicators, key=lambda x: x.get("id", "")), 1):
        ind_id = ind.get("id", "?")
        f = ind.get("file", "?")
        pv = ind.get("pine_version", "?")
        ln = ind.get("line_count", "?")
        nr = len(ind.get("roots") or [])
        nc = len(ind.get("composites") or [])
        ol = short(ind.get("one_line_purpose") or "", 80)
        lines.append(f"| {i} | `{ind_id}` | `{f}` | v{pv} | {ln} | {nr} | {nc} | {ol} |")
    lines.append("")
    lines.append("## Stage roadmap (this branch)")
    lines.append("")
    lines.append("- **Stage 1 (this PR)** — bible: roots/composites catalog, lineage cards, redundancy, glossary, VC diagnosis, YAML+JSON source of truth, memory files.")
    lines.append("- **Stage 2** — 3-4 lean Pine test indicators built only from roots, with provenance-named plots.")
    lines.append("- **Stage 3** — TradingView verification of every root (Anish-driven via TV MCP).")
    lines.append("- **Stage 4** — composite firing validation when roots align; lineage-card top-down diagnosis when they don't.")
    lines.append("- **Stage 5** — SOPs for root validation, composite validation, drift triage, offset triage.")
    lines.append("- **Stage 6** — file rename / move / archive / drift reconciliation. PR ready-for-review.")
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    if not YAML_PATH.exists():
        sys.stderr.write("ERROR: data/indicators.yaml not found. Run merge_extracts.py first.\n")
        return 1
    data = yaml.safe_load(YAML_PATH.read_text())
    DOCS.mkdir(parents=True, exist_ok=True)
    TREES_DIR.mkdir(parents=True, exist_ok=True)

    (DOCS / "roots.md").write_text(build_roots_md(data))
    (DOCS / "composites.md").write_text(build_composites_md(data))
    (DOCS / "redundancy.md").write_text(build_redundancy_md(data))

    trees = build_visual_trees(data)
    for ind_id, content in trees.items():
        (TREES_DIR / f"{ind_id}.txt").write_text(content)

    INDEX_PATH.write_text(build_index_md(data))

    print(f"Wrote docs/roots.md ({len(data.get('roots') or [])} roots)")
    print(f"Wrote docs/composites.md ({len(data.get('composites') or [])} composites)")
    print(f"Wrote docs/redundancy.md")
    print(f"Wrote {len(trees)} visual trees to docs/visual-trees/")
    print(f"Wrote {INDEX_PATH.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
