#!/usr/bin/env python3
"""
Build per-top-level-composite lineage cards from data/indicators.yaml.

Each lineage card walks the dependency expansion from a top-level composite down to roots,
showing canonical name, tier, lifecycle stage, offset, and a one-line definition at every level.

Output: docs/lineage/<canonical-id-flat>.md per top-level composite + docs/lineage/INDEX.md.

The bible's source of truth is data/indicators.yaml. This script is deterministic — re-running
it after a YAML change re-emits all cards consistently.

Usage:
    python3 tools/build_lineage_cards.py
"""

from __future__ import annotations
import os
import re
import sys
import yaml
from pathlib import Path
from collections import OrderedDict

REPO = Path(__file__).resolve().parent.parent
YAML_PATH = REPO / "data" / "indicators.yaml"
LINEAGE_DIR = REPO / "docs" / "lineage"


def slug(canonical: str) -> str:
    """Turn 'squarify::S1_SDUPER_BULL' into 'squarify__S1_SDUPER_BULL.md'."""
    return canonical.replace("::", "__").replace("/", "_") + ".md"


def header_line() -> str:
    return "Auto-generated by tools/build_lineage_cards.py from data/indicators.yaml. Do not edit by hand."


def find_root(roots, canonical):
    """Look up a root by id or by alias name."""
    for r in roots:
        if r.get("id") == canonical:
            return r
    return None


def find_composite(composites, canonical):
    for c in composites:
        if c.get("id") == canonical:
            return c
    return None


def render_card(top_level: dict, roots: list, composites: list) -> str:
    """Build a single lineage-card markdown for the given top-level composite."""
    cid = top_level.get("id", "(unknown)")
    tier = top_level.get("tier", "?")
    lifecycle = top_level.get("lifecycle_stage", 5)
    offset = top_level.get("plot_offset", "?")
    one_line = top_level.get("plain_english", top_level.get("composition", ""))
    if isinstance(one_line, dict):
        one_line = "(see composition expansion below)"

    lines = []
    lines.append(f"# Lineage Card — `{cid}`")
    lines.append("")
    lines.append(f"_{header_line()}_")
    lines.append("")
    lines.append(f"**Top-level composite:** `{cid}` &nbsp;&nbsp;`tier-{tier}` &nbsp;&nbsp;`stage-{lifecycle}` &nbsp;&nbsp;`offset={offset}`")
    lines.append("")
    lines.append(f"**One-line:** {one_line}")
    lines.append("")

    # Dependency expansion
    lines.append("## Dependency expansion")
    lines.append("")
    lines.append("```")
    expand_node(cid, roots, composites, lines, depth=0, visited=set())
    lines.append("```")
    lines.append("")

    # Root inventory (deduplicated leaves)
    lines.append("## Root inventory (deduplicated leaves)")
    lines.append("")
    leaves = collect_leaves(cid, roots, composites, set())
    if not leaves:
        lines.append("_(none — top-level may itself be a root, or composition is unresolved)_")
    else:
        for leaf in sorted(leaves):
            r = find_root(roots, leaf)
            if r:
                offset_r = r.get("plot_offset", 0)
                lines.append(f"- `{leaf}` &nbsp;&nbsp;`stage-{r.get('lifecycle_stage', 2)}` &nbsp;&nbsp;`offset={offset_r}`")
            else:
                lines.append(f"- `{leaf}` &nbsp;&nbsp;_(unresolved — not in roots catalog)_")
    lines.append("")

    # Offset ledger
    lines.append("## Offset ledger (for offset-bug triage)")
    lines.append("")
    offsets = collect_offsets(cid, roots, composites, set(), level=0)
    for indent, name, off in offsets:
        prefix = "  " * indent
        lines.append(f"- {prefix}`{name}` → offset `{off}`")
    lines.append("")

    # Decoupling proof
    lines.append("## Decoupling proof (per the lifecycle)")
    lines.append("")
    lines.append("- Each root calculated independently in stage 2 on this bar's confirmed close.")
    lines.append("- Each root's offset applied in stage 3.")
    lines.append("- Plots render in stage 4.")
    lines.append("- Composites read root booleans only at stage 5; no composite inspects root internals.")
    lines.append(f"- This composite (`{cid}`) reads its operands by name, never reaching into their calculations.")
    lines.append("")

    # Common failure modes
    lines.append("## Common failure modes")
    lines.append("")
    lines.append("If this composite fires (or fails to fire) unexpectedly, check in this order:")
    lines.append("")
    lines.append("1. **Offset mismatch** between this top-level and a child composite (compare offset ledger above).")
    lines.append("2. **Cross-indicator drift** on a shared root (see `docs/redundancy.md` — especially the PBJ / RVOL ladder / Unified Combo sections).")
    lines.append("3. **Namespace collision** pulling in the wrong implementation (e.g. `Pentagon` RVOL tier vs `anyBearPent` platform).")
    lines.append("4. **Parameter drift** — the same root may have different defaults across indicators (DISP σ-mult, GZI proximity, Long1/2 thresholds).")
    lines.append("")

    # Drift warnings if any
    drift = top_level.get("drift_warning")
    if drift:
        lines.append("## Drift warning")
        lines.append("")
        lines.append(f"- {drift}")
        lines.append("")

    return "\n".join(lines)


def expand_node(node_id, roots, composites, lines, depth, visited):
    """Recursively expand a composite node into its operands."""
    if node_id in visited:
        lines.append("  " * depth + f"└── `{node_id}` (cycle — already expanded)")
        return
    visited = visited | {node_id}

    indent = "  " * depth
    r = find_root(roots, node_id)
    if r:
        # Leaf
        offset = r.get("plot_offset", 0)
        defn = (r.get("plain_english") or "")[:80]
        lines.append(f"{indent}└── ROOT  `{node_id}`  offset={offset}  — {defn}")
        return

    c = find_composite(composites, node_id)
    if not c:
        lines.append(f"{indent}└── `{node_id}` (unresolved — not in roots or composites)")
        return

    tier = c.get("tier", "?")
    offset = c.get("plot_offset", "?")
    one_line = c.get("plain_english", "")
    if not one_line:
        comp = c.get("composition") or c.get("composition_summary", "")
        if isinstance(comp, str):
            one_line = comp[:100]
    lines.append(f"{indent}● `{node_id}`  tier-{tier}  offset={offset}")
    if one_line:
        lines.append(f"{indent}  one-line: {one_line[:120]}")

    # Walk operands
    comp = c.get("composition")
    operands = []
    if isinstance(comp, dict):
        ops = comp.get("operands", [])
        for op in ops:
            if isinstance(op, str):
                operands.append(op)
            elif isinstance(op, dict):
                if "of" in op:
                    operands.append(op["of"])
                elif "operands" in op:
                    for sub in op["operands"]:
                        if isinstance(sub, str):
                            operands.append(sub)

    # If operands not extractable from structured composition, look for `operands` field
    if not operands:
        ops = c.get("operands", [])
        if isinstance(ops, list):
            for op in ops:
                if isinstance(op, str):
                    operands.append(op)

    for op in operands:
        # Operand may be a canonical id or a local source-level name
        if "::" in op:
            expand_node(op, roots, composites, lines, depth + 1, visited)
        else:
            lines.append(f"{indent}  └── (source-level operand) `{op}` — see {find_indicator_for_operand(op, roots, composites)} for canonical")


def find_indicator_for_operand(op, roots, composites):
    """Heuristic: find the canonical name a source-level operand maps to."""
    # Check root aliases
    for r in roots:
        for alias in r.get("aliases") or []:
            if isinstance(alias, dict) and alias.get("name") == op:
                return r.get("id")
            elif isinstance(alias, str) and alias == op:
                return r.get("id")
    return "(canonical not found)"


def collect_leaves(node_id, roots, composites, visited):
    """Return the set of canonical root ids reachable from this node."""
    if node_id in visited:
        return set()
    visited = visited | {node_id}

    if find_root(roots, node_id):
        return {node_id}

    c = find_composite(composites, node_id)
    if not c:
        return set()

    leaves = set()
    operands = []
    comp = c.get("composition")
    if isinstance(comp, dict):
        ops = comp.get("operands", [])
        for op in ops:
            if isinstance(op, str) and "::" in op:
                operands.append(op)
            elif isinstance(op, dict):
                if "of" in op:
                    operands.append(op["of"])
                elif "operands" in op:
                    for sub in op["operands"]:
                        if isinstance(sub, str) and "::" in sub:
                            operands.append(sub)

    for op in operands:
        leaves.update(collect_leaves(op, roots, composites, visited))

    return leaves


def collect_offsets(node_id, roots, composites, visited, level):
    """Yield (depth, name, offset) tuples for the offset ledger."""
    if node_id in visited:
        return []
    visited = visited | {node_id}

    out = []
    r = find_root(roots, node_id)
    if r:
        out.append((level, node_id, r.get("plot_offset", 0)))
        return out

    c = find_composite(composites, node_id)
    if not c:
        return out

    out.append((level, node_id, c.get("plot_offset", "?")))

    operands = []
    comp = c.get("composition")
    if isinstance(comp, dict):
        ops = comp.get("operands", [])
        for op in ops:
            if isinstance(op, str) and "::" in op:
                operands.append(op)
            elif isinstance(op, dict):
                if "of" in op:
                    operands.append(op["of"])
                elif "operands" in op:
                    for sub in op["operands"]:
                        if isinstance(sub, str) and "::" in sub:
                            operands.append(sub)

    for op in operands:
        out.extend(collect_offsets(op, roots, composites, visited, level + 1))

    return out


def is_top_level(c):
    """A composite is top-level if it's plotted with an alertcondition or marked T1/T2/S* numbered."""
    if c.get("has_alertcondition"):
        return True
    cid = c.get("id", "")
    # Top-level Squarify and B2B PUP numbered composites
    if re.search(r"::S\d+_", cid):
        return True
    # Top-level Ultra Combo / TNT-OD signals
    top_keywords = ["MEGA", "OPENER", "GRAIL", "FUSE", "DYNAMITE", "WBUSH", "T1_OPENING", "T2_OPENING",
                    "FIRE_FULL", "SDUPER", "SUPER_BULL", "HW_BULL", "SUPER_TNT",
                    "B2B_NAPALM", "RC_NPM_TNT", "CATALYST", "IGNITE",
                    "B2B_PUP", "B2B_PPD", "S1_HEAVY", "S2_HEAVY", "S3_HEAVY",
                    "ALL_THREE", "TB_SELL", "FOSTER_BUY",
                    "T3_LADDER", "T3_SUPER_BUY", "T3_SUPER_SELL"]
    return any(k in cid for k in top_keywords)


def main():
    if not YAML_PATH.exists():
        print(f"ERROR: {YAML_PATH} not found", file=sys.stderr)
        sys.exit(1)

    data = yaml.safe_load(YAML_PATH.read_text())
    roots = data.get("roots", [])
    composites = data.get("composites", [])
    chains = data.get("chains", [])

    LINEAGE_DIR.mkdir(parents=True, exist_ok=True)

    top_level = [c for c in composites if is_top_level(c)]
    # Also include all chains as top-level
    top_level.extend(chains)

    print(f"Found {len(top_level)} top-level composites/chains.")

    index_lines = ["# Lineage Cards — Index", "", f"_{header_line()}_", "",
                   "Each card walks the dependency expansion from a top-level composite down to roots.",
                   "Per-card sections: dependency expansion, root inventory, offset ledger, decoupling proof, common failure modes.",
                   "", "| Top-level composite | Tier | Indicator | Offset | One-line |",
                   "|---|---|---|---|---|"]

    written = 0
    for c in top_level:
        cid = c.get("id", "")
        if not cid:
            continue
        card = render_card(c, roots, composites)
        out_path = LINEAGE_DIR / slug(cid)
        out_path.write_text(card)
        written += 1

        tier = c.get("tier", "?")
        ind = c.get("in_indicator", "?")
        offset = c.get("plot_offset", "?")
        one_line = (c.get("plain_english") or "")[:80]
        index_lines.append(f"| [`{cid}`]({slug(cid)}) | {tier} | {ind} | {offset} | {one_line} |")

    (LINEAGE_DIR / "INDEX.md").write_text("\n".join(index_lines) + "\n")
    print(f"Wrote {written} lineage cards + INDEX.md to {LINEAGE_DIR}/")


if __name__ == "__main__":
    main()
